# Generated by Django 4.2.7 on 2025-08-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aichat_aiknowledgebase_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
