# Generated by Django 4.2.7 on 2025-08-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('github', 'GitHub'), ('microsoft_teams', 'Microsoft Teams'), ('jira', 'Jira'), ('trello', 'Trello'), ('asana', 'Asana'), ('zapier', 'Zapier'), ('webhook', 'Webhook'), ('custom', 'Custom Integration')], max_length=50)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_interval', models.IntegerField(default=3600, help_text='Sync interval in seconds')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('events', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration Webhook',
                'verbose_name_plural': 'Integration Webhooks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('root_folder_id', models.CharField(blank=True, max_length=100)),
                ('sync_folders', models.JSONField(blank=True, default=list)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Google Drive Integration',
                'verbose_name_plural': 'Google Drive Integrations',
            },
        ),
    ]
